import type { Metadata } from 'next';
import SmoothScrollGSAP from '../components/smoothscroll';
import './globals.css';

export const metadata: Metadata = {
  title: 'Patrick Lyons',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-50">
        <SmoothScrollGSAP /> {children}
      </body>
    </html>
  );
}
